"""create schema relationships table

Revision ID: 21783c690530
Revises: 9b5e6a582194
Create Date: 2026-07-13 20:16:45.181966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21783c690530'
down_revision: Union[str, Sequence[str], None] = '9b5e6a582194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'source_table', 'source_column', 'target_table', 'target_column', name='uq_schema_relationship')
    )
    op.create_index(op.f('ix_schema_relationships_connection_id'), 'schema_relationships', ['connection_id'], unique=False)
    op.create_index(op.f('ix_schema_relationships_id'), 'schema_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_schema_relationships_source_table'), 'schema_relationships', ['source_table'], unique=False)
    op.create_index(op.f('ix_schema_relationships_target_table'), 'schema_relationships', ['target_table'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_relationships_target_table'), table_name='schema_relationships')
    op.drop_index(op.f('ix_schema_relationships_source_table'), table_name='schema_relationships')
    op.drop_index(op.f('ix_schema_relationships_id'), table_name='schema_relationships')
    op.drop_index(op.f('ix_schema_relationships_connection_id'), table_name='schema_relationships')
    op.drop_table('schema_relationships')
    # ### end Alembic commands ###
