"""create schema tables and columns

Revision ID: 9b5e6a582194
Revises: c0fd676f2c3e
Create Date: 2026-07-13 20:04:04.505130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5e6a582194'
down_revision: Union[str, Sequence[str], None] = 'c0fd676f2c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False, comment="PostgreSQL schema (e.g. 'public'). Reserved for future multi-schema support."),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of when this table was first ingested into the metadata catalog.'),
    sa.ForeignKeyConstraint(['connection_id'], ['database_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'schema_name', 'table_name', name='uq_schema_table')
    )
    op.create_index(op.f('ix_schema_tables_connection_id'), 'schema_tables', ['connection_id'], unique=False)
    op.create_index(op.f('ix_schema_tables_id'), 'schema_tables', ['id'], unique=False)
    op.create_table('schema_columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False, comment='Whether the column allows NULL values. Sourced from information_schema.columns.'),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['schema_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_columns_id'), 'schema_columns', ['id'], unique=False)
    op.create_index(op.f('ix_schema_columns_table_id'), 'schema_columns', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_columns_table_id'), table_name='schema_columns')
    op.drop_index(op.f('ix_schema_columns_id'), table_name='schema_columns')
    op.drop_table('schema_columns')
    op.drop_index(op.f('ix_schema_tables_id'), table_name='schema_tables')
    op.drop_index(op.f('ix_schema_tables_connection_id'), table_name='schema_tables')
    op.drop_table('schema_tables')
    # ### end Alembic commands ###
